AlignHash:
  Enabled: false

AlignParameters:
  Enabled: false

Documentation:
  Enabled: false

DotPosition:
  Enabled: false

LineLength:
  Max: 120

MultilineBlockChain:
  Enabled: false

SignalException:
  Enabled: false

StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

